// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:dotenv/dotenv.dart' show DotEnv;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Loaded from `.env` at app startup (see `lib/main.dart`).
///
/// Values fall back to the API keys / IDs originally generated by the
/// FlutterFire CLI so the app still boots even when `.env` is not present
/// (e.g. on a device, where it is not bundled).
final DotEnv firebaseEnv = DotEnv(quiet: true);

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Values are resolved from `firebaseEnv` (populated from `.env`) with the
/// generated constants as fallbacks.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android {
    final apiKey =
        firebaseEnv['ANDROID_API_KEY'] ??
        '';
    final appId =
        firebaseEnv['ANDROID_APP_ID'] ??
        '';
    final messagingSenderId =
        firebaseEnv['GCM_SENDER_ID'] ?? '';
    final projectId = firebaseEnv['PROJECT_ID'] ?? '';
    final storageBucket =
        firebaseEnv['STORAGE_BUCKET'] ?? '';
    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket,
    );
  }

  static FirebaseOptions get ios {
    final apiKey =
        firebaseEnv['IOS_API_KEY'] ?? '';
    final appId =
        firebaseEnv['IOS_APP_ID'] ??
        '';
    final messagingSenderId =
        firebaseEnv['GCM_SENDER_ID'] ?? '';
    final projectId = firebaseEnv['PROJECT_ID'] ?? '';
    final storageBucket =
        firebaseEnv['STORAGE_BUCKET'] ?? '';
    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket,
      iosBundleId: 'com.example.stackprep',
    );
  }
}